"""
Lightweight deepfake detection.

Uses a pre-trained EfficientNet-B4 binary classifier fine-tuned on
FaceForensics++ (via timm). Falls back to a frequency-domain heuristic
if model weights are not present.
"""

import cv2
import numpy as np
from pathlib import Path

MODEL_DIR = Path(__file__).parent.parent / "models"
DETECTOR_WEIGHTS = MODEL_DIR / "deepfake_detector.pth"


def _freq_heuristic(img_bgr: np.ndarray) -> tuple[float, str]:
    """
    Frequency-domain heuristic: real photos have a characteristic 1/f
    power spectrum. Deepfakes generated by GANs often have spectral artifacts.

    Returns (score 0–1, label) where score > 0.5 means likely synthetic.
    """
    gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY).astype(np.float32)
    dft = np.fft.fft2(gray)
    shifted = np.fft.fftshift(dft)
    magnitude = np.log1p(np.abs(shifted))

    h, w = magnitude.shape
    cy, cx = h // 2, w // 2
    radius = min(h, w) // 8

    Y, X = np.ogrid[:h, :w]
    mask = (X - cx) ** 2 + (Y - cy) ** 2 <= radius ** 2
    center_energy = magnitude[mask].mean()
    total_energy = magnitude.mean()

    ratio = center_energy / (total_energy + 1e-8)
    # Real images tend to concentrate energy at low frequencies (high ratio).
    # GAN outputs often leak energy at mid/high frequencies (lower ratio).
    score = float(np.clip(1.0 - (ratio - 1.0) / 3.0, 0.0, 1.0))
    label = "Likely Synthetic" if score > 0.5 else "Likely Real"
    return score, label


def _model_predict(img_bgr: np.ndarray) -> tuple[float, str]:
    import torch
    import timm
    from torchvision import transforms
    from PIL import Image

    model = timm.create_model("efficientnet_b4", pretrained=False, num_classes=2)
    state = torch.load(DETECTOR_WEIGHTS, map_location="cpu")
    model.load_state_dict(state)
    model.eval()

    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])

    pil = Image.fromarray(cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB))
    tensor = transform(pil).unsqueeze(0)

    with torch.no_grad():
        logits = model(tensor)
        prob = torch.softmax(logits, dim=1)[0, 1].item()

    label = "Likely Synthetic" if prob > 0.5 else "Likely Real"
    return prob, label


def analyze(img_bgr: np.ndarray) -> dict:
    """
    Run deepfake detection on an image.

    Returns:
        {
            "score": float (0–1, higher = more likely synthetic),
            "label": str,
            "method": str,
        }
    """
    if DETECTOR_WEIGHTS.exists():
        try:
            score, label = _model_predict(img_bgr)
            return {"score": score, "label": label, "method": "EfficientNet-B4 classifier"}
        except Exception:
            pass

    score, label = _freq_heuristic(img_bgr)
    return {"score": score, "label": label, "method": "Frequency-domain heuristic (fallback)"}
